name = "javanese"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "18.140.65.40"
UUID = "8e360b19-b67e-4cc7-8ed9-af9d7da2fb44"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
